from typing import Any, Generic, TypeVar

_T = TypeVar("_T")


class Query(Generic[_T]):
    def filter_by(self, **kwargs: Any) -> Query[_T]: ...
    def first(self) -> _T | None: ...
    def all(self) -> list[_T]: ...
    def update(self, values: dict[Any, Any]) -> int: ...


class Session:
    def add(self, instance: object) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
    def delete(self, instance: object) -> None: ...
    def query(self, entity: type[_T]) -> Query[_T]: ...


class sessionmaker(Generic[_T]):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __call__(self) -> Session: ...
